FROM node:alpine

WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
COPY nodemon.json ./
CMD npm config set cache-min 9999999 && \
    npm install && \
    npx wait-port rabbit:5672 && \
    npm run start:dev