FROM node:alpine as build

WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
COPY ./src ./src
RUN npm install
RUN npm run build

FROM node:alpine
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install --only=production
COPY --from=build /usr/src/app/build ./build

CMD npx wait-port rabbit:5672 && \
    npm start